name: moviefy_oropockets
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0-212.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_native_splash: ^2.2.11

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_native_splash:
  color: '#007CFF'
  image: 'assets/images/logo.png'
  android_12:
   color: '#007CFF'
   image: 'assets/images/logo.png'

flutter:
  uses-material-design: true



  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Bold.ttf
          weight: 700
        - asset: assets/font/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Inter-ExtraLight.ttf
          weight: 100
        - asset: assets/font/Inter-Light.ttf
          weight: 200
        - asset: assets/font/Inter-Medium.ttf
          weight: 300
        - asset: assets/font/Inter-Regular.ttf
          weight: 400
        - asset: assets/font/Inter-SemiBold.ttf
          weight: 600